language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
# ---------------------------------
# Needed to get Python 3.7 support?
dist: xenial
sudo: true
# ---------------------------------
install:
  - pip install tox
script:
  - "echo TRAVIS_BRANCH: $TRAVIS_BRANCH"
  - tox -e py
