environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python37-x64"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "echo APPVEYOR_PULL_REQUEST_NUMBER: %APPVEYOR_PULL_REQUEST_NUMBER%"
  - "echo APPVEYOR_REPO_BRANCH: %APPVEYOR_REPO_BRANCH%"
  - "python --version"
  - "pip install tox"

build: off

cache:
  - '%LOCALAPPDATA%\pip\Cache'

test_script:
    - ps: |
        function should_run_tests {
            if ("$env:APPVEYOR_PULL_REQUEST_NUMBER" -eq "") {
                echo "Not a pull request - running tests"
                return $true
            }
            echo "$env:APPVEYOR_PULL_REQUEST_NUMBER based on branch $env:APPVEYOR_REPO_BRANCH"
            git fetch -q origin +refs/heads/$env:APPVEYOR_REPO_BRANCH
            $changes = (git diff --name-only HEAD (git merge-base HEAD FETCH_HEAD))
            echo "Files changed:"
            echo $changes
            $important = $changes | Where-Object { $_ -NotLike "*.rst" } |
                                    Where-Object { $_ -NotLike "docs*" } |
                                    Where-Object { $_ -NotLike "news*" } |
                                    Where-Object { $_ -NotLike ".github*" }
            if (!$important) {
                echo "Only documentation changes - skipping tests"
                return $false
            }

            echo "Pull request $env:APPVEYOR_PULL_REQUEST_NUMBER alters code - running tests"
            return $true
        }

        if (should_run_tests) {
            tox -e py
        }
