environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python37-x64"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "echo APPVEYOR_PULL_REQUEST_NUMBER: %APPVEYOR_PULL_REQUEST_NUMBER%"
  - "echo APPVEYOR_REPO_BRANCH: %APPVEYOR_REPO_BRANCH%"
  - "python --version"
  - "pip install tox"

build: off

cache:
  - '%LOCALAPPDATA%\pip\Cache'

test_script:
    - ps: |
        echo $env:APPVEYOR_REPO_BRANCH
        tox -e py
